### ISSUE TITLE
Using Reflections in order to reduce code in main

### ISSUE THREAD

**Issue by danthe1st** [JavaChat/OakBot#45]
Every command of the Bot is added manually in the main class.
This can also be done by adding an Annotation and annotating all Commands with that.
Using [Reflections](https://github.com/ronmamo/reflections), it is possible to scan for Classes that are annotated with a specified annotation. Using Reflection, it is possible to create an instance from the Class object.

**Comment by mangstadt** [comment]
Very nice idea, thanks for the suggestion.

Many of the command classes have constructors which take multiple parameters.  I wonder how it would be possible to provide those parameters values when instantiating the objects via reflection.

I think a dependency injection framework like Spring would help with this, but I don't know much about it.

**Comment by danthe1st** [comment]
It is possible to check if a constructor with specified arguments exists, but I think in your case it is better to test for 2 constructors: 

- no-args contructor 

- A constructor that rescieves props and loads the arguments for the Commands from that.

**Comment by mangstadt** [comment]
I think I'm going to try using Spring's dependency injection to see how that works out. The application context XML file is kind of ugly, but it would give users the ability to define their own commands without needing to modify the source code.

This gives you more control over how an object is instantiated. Many of Oak's command objects share the same instances of certain objects.
